# Import libraries

In [1]:
import numpy  as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
# data file
df = pd.read_csv("store.csv")
df.head(2)

,order_id,order_date,name,city,state,post_code,region,category,sub_category,sales,qty,profit
0,CA-2016-155488,2016-11-13 00:00:00,Frank Merwin,Vancouver,Washington,98661.0,West,Office Supplies,Art,44.02,2,11.45
1,CA-2015-124891,2015-07-31 00:00:00,Rick Hansen,New York City,New York,NaN,East,Technology,Accessories,2309.65,7,762.18

In [3]:
car = pd.read_csv("car_average.csv")
car.head(2)

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
0,18.0,8,307.0,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165,3693,11.5,70,1,buick skylark 320

In [ ]:
# bar chart
print(df.groupby("region")['sales'].sum())
df.groupby("region")['sales'].sum().plot(kind="bar")

In [ ]:
# barh chart
df.groupby("region")['sales'].sum().plot(kind="barh")

In [ ]:
data = df.groupby("region")['sales'].sum().sort_values()
data.plot(kind="barh")

In [ ]:
# barh chart formating
plt.figure(figsize=(9,3))
df.groupby("region")['sales'].sum().plot(kind="barh")

In [ ]:
# barh chart formating - color could be black,blue,yello,pink,red, gray hax code etc
plt.figure(figsize=(9,3))
df.groupby("region")['sales'].sum().plot(kind="barh",color="#3ecfc3")

In [ ]:
# barh chart formating - titles and labels

df.groupby("region")['sales'].sum().plot(kind="barh")
plt.title('Region wise total sales')
plt.xlabel("Sales")
plt.ylabel("Regions")

In [ ]:
# barh chart formating - show 

df.groupby("region")['sales'].sum().plot(kind="barh")
plt.title('Region wise total sales')
plt.xlabel("Sales")
plt.ylabel("Regions")
plt.show()

In [ ]:
# barh chart formating - save a chart

df.groupby("region")['sales'].sum().plot(kind="barh")
plt.title('Region wise total sales')
plt.xlabel("Sales")
plt.ylabel("Regions")
plt.savefig("region wise total sales.png")

In [ ]:
# barh chart formating

plt.figure(figsize=(9,6))

df.groupby("sub_category")['sales'].sum().sort_values().plot(kind="barh",color="gray")

plt.title("Sub category wise total sales",size=15,color="blue",fontweight="bold")
plt.xlabel("Sales")
plt.ylabel("Sub category")
plt.show()

In [ ]:
# Create a bar chart of top 10 cities with the highest total sales

In [ ]:
# show top five most profitable subcategories

In [ ]:
# Show year wise total sales (year should be in ascending order)

In [ ]:
# Pie chart
print(df.category.value_counts())
df.category.value_counts().plot(kind="pie")
plt.show()

In [ ]:
# Line chart
df.info()

In [ ]:
df['order_date'] = pd.to_datetime(df['order_date'])
df['year'] = df['order_date'].dt.year
df['month'] = df['order_date'].dt.month

In [ ]:
df.head()

In [ ]:
print(df.groupby(['year','month'])['sales'].sum())
plt.figure(figsize=(12,4))
df.groupby(['year','month'])['sales'].sum().plot(kind='line')
plt.show()

In [ ]:
plt.figure(figsize=(12,4))

df.groupby(['year','month'])['sales'].sum().plot(kind='area',color='gray')
plt.show()

In [ ]:
profit =  df[['order_date','profit']].sort_values(by='order_date').reset_index()['profit']
profit

In [ ]:
data = [45,80,12,34,67]
data = pd.Series(data)
print(data)
print(data.cumsum())

In [ ]:
profit.cumsum().plot()
plt.show()

# Hist plot

In [ ]:
df.qty.plot(kind='hist')
plt.show()

In [ ]:
car['horsepower'].plot(kind='hist',bins=15)
plt.show()

# Box plot

In [ ]:
df.qty.plot(kind='box')
plt.show()

In [ ]:
car['horsepower'].plot(kind='box',vert=False)
plt.show()

# Scatter plot chart

In [ ]:
car = pd.read_csv("car_average.csv")
car.head(2)

In [ ]:
car.plot(kind='scatter',x='horsepower',y='mpg')
plt.show()

In [ ]:
car.plot(kind='scatter',x="weight",y='horsepower')
plt.show()