In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

from sklearn.pipeline import Pipeline
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler , OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score , root_mean_squared_error , mean_absolute_error , mean_squared_error

In [3]:
df = pd.read_csv("house_price.csv")

In [4]:
df.head()

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 545 entries, 0 to 544
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   price             545 non-null    int64
 1   area              545 non-null    int64
 2   bedrooms          545 non-null    int64
 3   bathrooms         545 non-null    int64
 4   stories           545 non-null    int64
 5   mainroad          545 non-null    object
 6   guestroom         545 non-null    object
 7   basement          545 non-null    object
 8   hotwaterheating   545 non-null    object
 9   airconditioning   545 non-null    object
 10  parking           545 non-null    int64
 11  prefarea          545 non-null    object
 12  furnishingstatus  545 non-null    object
dtypes: int64(6), object(7)
memory usage: 55.5+ KB

In [6]:
df.isnull().sum()

price               0
area                0
bedrooms            0
bathrooms           0
stories             0
mainroad            0
guestroom           0
basement            0
hotwaterheating     0
airconditioning     0
parking             0
prefarea            0
furnishingstatus    0
dtype: int64

# category and numerical feature list

In [7]:
categorical_features =  ['mainroad', 'guestroom', 'basement', 'hotwaterheating', 'airconditioning', 'prefarea', 'furnishingstatus']
numerical_features =  ['area', 'bedrooms', 'bathrooms', 'stories', 'parking']

In [8]:
df.describe().round(2)

             price      area  bedrooms  bathrooms  stories  parking
count       545.00    545.00    545.00     545.00   545.00   545.00
mean    4766729.25   5150.54      2.97       1.29     1.81     0.69
std     1870439.62   2170.14      0.74       0.50     0.87     0.86
min     1750000.00   1650.00      1.00       1.00     1.00     0.00
25%     3430000.00   3600.00      2.00       1.00     1.00     0.00
50%     4340000.00   4600.00      3.00       1.00     2.00     0.00
75%     5740000.00   6360.00      3.00       2.00     2.00     1.00
max    13300000.00  16200.00      6.00       4.00     4.00     3.00

In [9]:
# for i in numerical_features:
#     sns.boxplot(df[i])
#     plt.show()

## Split the data for training and testing

In [10]:
x = df.drop(columns='price')
y = df['price']

In [11]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [12]:
# x_train

In [13]:
# y_train

In [14]:
# x_test

In [15]:
# y_test

In [16]:
# creating pipeline
preprocessor = ColumnTransformer([
    ("scaler",StandardScaler(),numerical_features),
      ("encoder",OneHotEncoder(),categorical_features)
      ])

## making a pipeline

In [17]:
pipe = Pipeline([
    ("scale and encode", preprocessor),
    ("model",LinearRegression())
])

In [18]:
pipe.fit(x_train,y_train)

Pipeline(steps=[('scale and encode',
                 ColumnTransformer(transformers=[('scaler', StandardScaler(),
                                                  ['area', 'bedrooms',
                                                   'bathrooms', 'stories',
                                                   'parking']),
                                                 ('encoder', OneHotEncoder(),
                                                  ['mainroad', 'guestroom',
                                                   'basement',
                                                   'hotwaterheating',
                                                   'airconditioning',
                                                   'prefarea',
                                                   'furnishingstatus'])])),
                ('model', LinearRegression())])

In [19]:
prediction = pipe.predict(x_test)

## checking model accuracy

In [20]:
mean_absolute_error(y_test,prediction)

970043.4039201646

In [21]:
mean_squared_error(y_test,prediction)

1754318687330.6692

In [22]:
root_mean_squared_error(y_test,prediction)

1324506.9600914407

In [23]:
r2_score(y_test,prediction)

0.6529242642153174

## Saving the model in file

In [24]:
import joblib

In [25]:
joblib.dump(pipe,"model.pkl")

['model.pkl']

In [28]:
loaded_model =  joblib.load("model.pkl")

In [29]:
loaded_model.predict(x_test)

array([5164653.90033967, 7224722.29802166, 3109863.24240338,
       4612075.32722559, 3294646.25725956, 3532275.09556558,
       5611774.56836474, 6368145.98732718, 2722856.95689986,
       2629405.61585783, 9617039.50315578, 2798087.30447888,
       3171096.76847064, 3394639.09125529, 3681088.65424276,
       5263187.74621486, 3035963.47612386, 4786122.8004005 ,
       4349551.9200572 , 3572362.09930451, 5774875.21395649,
       5886993.57919883, 2730836.19518459, 4727316.47323636,
       5244847.52716799, 7555324.21605601, 3220790.84680269,
       5191898.79934208, 8143726.91009782, 3398814.09825036,
       6490693.05027926, 3315105.90747811, 6708457.36761325,
       4201738.21071675, 3557571.06735186, 5836974.50478626,
       4808660.67448475, 4362878.73613262, 3191242.95701508,
       4596554.93225239, 4566042.8604841 , 3517779.52374149,
       7205844.79365835, 3983597.27861103, 3749338.70271055,
       4274731.09125895, 6757442.10783741, 4037320.43665851,
       3769334.90397125, 3417627.44377157, 7268416.6764461 ,
       2802534.35431385, 4341750.61420451, 4516422.15345642,
       3679997.65037847, 2678959.06481153, 7498029.17782458,
       2920366.45493168, 4239582.0596018 , 2766467.48467034,
       4841309.85933273, 3584359.56014923, 5142140.84897579,
       4221869.20996263, 4698408.50824081, 4662380.98564313,
       7177841.51216424, 3452198.91383761, 5902436.91361411,
       6198094.31822812, 4773218.99689078, 5178933.32585697,
       4490410.96106558, 7968737.41567512, 3519394.94792196,
       5501905.04909554, 3947055.15571396, 4714056.36707951,
       4792291.26764381, 4250596.74659377, 7718149.1935735 ,
       4053241.11775758, 6453918.60757726, 5355571.58680278,
       2755188.2917527 , 6796008.0979336 , 2607277.38176332,
       3679738.85761988, 7968276.12638737, 8078480.59500816,
       3266213.77309708, 5897888.53031041, 3569461.07439185,
       3868964.98032521, 7584429.5312489 , 4740586.43771692,
       5139372.69032253, 6423485.10228601, 4914078.82258489,
       5982087.31289315, 3855027.32194281, 6420308.27282365,
       3749108.5131483 , 5998642.37204433, 4973331.10029252,
       4336650.86896383, 7059062.72274841, 6398940.86831986,
       6363889.85312644])

## checking with your own data

In [30]:
data = pd.DataFrame([[8000, 3, 1, 5, 'yes', 'no', 'yes', 'yes', 'yes', 1, 'yes', 'furnished']],
                    columns=x_test.columns)

In [31]:
data

,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,8000,3,1,5,yes,no,yes,yes,yes,1,yes,furnished

In [32]:
loaded_model.predict(data)

array([8598926.88349948])